name: Build 🔨

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      build_version:
        required: true
        type: string

jobs:
  build:
    name: Build 🔨
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Init Runner ⚙️
        uses: UnterrainerInformatik/init-runner-action@master

      - name: Set up Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Update version in package.json 💾
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.build_version }}

      - name: Install dependencies from lockfile ⚙️
        run: npm ci

      - name: build (build) 🔨
        run: npm run build

      - name: Fill version.js file
        env:
          MAJOR_VERSION: ${{ inputs.major_version }}
          MINOR_VERSION: ${{ inputs.minor_version }}
          BUILD_VERSION: ${{ inputs.build_version }}
        run: |
          mkdir -p ./dist
          cat <<EOF > ./dist/version.js
          window.version = (() => {
            return {
              VERSION: '${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}',
              MAJOR_VERSION: '${MAJOR_VERSION}',
              MINOR_VERSION: '${MINOR_VERSION}',
              BUILD_VERSION: '${BUILD_VERSION}'
            }
          })()
          EOF

      - name: Upload build artifacts ⬆️
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
